### ISSUE TITLE
Придумать способ учитывание семантики в решени

### ISSUE THREAD

**Issue by bmsdave** [piterjs/editor#10]
Сейчас задания могут быть решены с помощью нехитрого подхода.
Все блоки рисовать с `position: fixed;` 
```CSS
.blabla{
position: fixed;
top: 0;
left: 0;
width: 200px;
right: 200px;
}
```

Нужно придумать логику, по которой будет учитываться семантика и responsive дизайна
